spring.application.name=MS-NOTIFICACIONES
server.port=8086

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/db_notificaciones
spring.r2dbc.username=admin
spring.r2dbc.password=admin

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.sql.init.mode=always

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=71b49b4e19bf57
spring.mail.password=20b50ea112fa32
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.debug=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000